// Read-only QA of files generated by the application, not an application dependency.
import fs from 'node:fs/promises';
import path from 'node:path';
import {FileBlob, SpreadsheetFile} from '@oai/artifact-tool';
const dir=path.resolve('.local-dev/monthly-export-implementation-20260927');
for(const name of ['personal','group']) {
  const book=await SpreadsheetFile.importXlsx(await FileBlob.load(path.join(dir,name+'.xlsx')));
  const image=await book.render({sheetName:'月案01',range:'A1:BT85',scale:1.4,format:'png'});
  await fs.writeFile(path.join(dir,name+'-excel.png'),new Uint8Array(await image.arrayBuffer()));
}
