const assert = require('node:assert/strict');
const m = require('./core.js');
let rows=m.sample(), p=m.validate(rows);
assert.equal(p.canCommit,true);assert.equal(p.children.length,3);assert.equal(p.families.length,2);
assert.deepEqual(p.children.map(r=>r['園児整理番号']),['C001','C002','C003']);
assert.deepEqual(p.children.map(r=>r['家庭整理番号']),['F001','F001','F002']);
assert.deepEqual(p.families.map(f=>f.data['家庭名']),['見本 花','見本 光']);
assert.equal(p.children[1]['家庭名'],'見本 花');
assert.equal(m.validate([]).canCommit,false);
assert.equal(m.fields.length,38);
for(const key of ['園児整理番号','家庭整理番号','家庭名'])assert(!m.fields.some(f=>f.key===key));
assert.equal(m.fields.find(f=>f.key==='きょうだいグループ').required,false);
rows=m.sample();rows[2]['姓']='手本';p=m.validate(rows);assert.deepEqual(p.families.map(f=>f.data['家庭名']),['見本','手本']);
rows=m.sample();rows[2]['名']='花';p=m.validate(rows);assert.equal(new Set(p.families.map(f=>f.data['家庭名'])).size,2);assert.equal(p.families[1].data['家庭名'],'見本 花（F002）');
rows=m.sample();rows.forEach(r=>r['きょうだいグループ']='');p=m.validate(rows);assert.equal(p.families.length,3);
rows=m.sample();rows[1]['家庭電話番号']='other';assert(m.validate(rows).errors.some(e=>e.column==='家庭電話番号'));
rows=m.sample();rows[1]['家庭住所']='';assert.equal(m.validate(rows).families[0].data['家庭住所'],rows[0]['家庭住所']);
rows=m.sample();rows[0]['家庭電話番号']=12345;assert(m.validate(rows).errors.some(e=>e.column==='家庭電話番号'));
rows=m.sample();rows[0]['家庭電話番号']='000-0000-0001';assert.equal(m.validate(rows).canCommit,true);
rows=m.sample();rows[0]['生年月日']='2022-02-30';assert(m.validate(rows).errors.some(e=>e.column==='生年月日'));
rows=m.sample();rows[0]['保護者①名']='';assert(m.validate(rows).errors.some(e=>e.column==='保護者①姓・名'));
rows=m.sample();rows.push({...rows[0]});assert(m.validate(rows).errors.some(e=>e.message.includes('入力内容がすべて同じ')));
rows=m.sample();rows[2]['姓カナ']=rows[0]['姓カナ'];rows[2]['名カナ']=rows[0]['名カナ'];rows[2]['生年月日']=rows[0]['生年月日'];p=m.validate(rows);assert(p.canCommit);assert(p.warnings.length);assert.equal(p.children.length,3);
const sequence={child:0,family:0}, assignment=m.createAssignment(sequence);
rows=m.sample();const before=m.validate(rows,assignment);rows[0]['名']='春花';const after=m.validate(rows,assignment);
assert.equal(before.children[0]['園児整理番号'],after.children[0]['園児整理番号']);assert.equal(after.families[0].data['家庭名'],'見本 春花');
const other=m.validate(m.sample(),m.createAssignment(sequence));assert.equal(other.children[0]['園児整理番号'],'C004');assert.equal(other.families[0].key,'F003');
console.log('PASS: automatic IDs, surname/full-name/collision naming, explicit siblings, separate blank groups, stable IDs during edits, separate import batches, duplicates, and existing field validation.');
